FROM geerlingguy/php-apache:latest

RUN rm /var/www/html/index.html
COPY index.php ./src/var/www/html/index.php

COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/sites-enabled/000-default.conf

FROM mysql:5.7.25
ENV MYSQL_ALLOW_EMPTY_PASSWORD='yes'